apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          envFrom:
            - configMapRef:
                name: app-config
